name: Update CN ip

on:
  workflow_dispatch:
  schedule:
  # Run at 00:00 every Monday.
    - cron: '0 0 * * 1'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Set variables
        run: |
          echo "COMMIT_MSG=$(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
          git config user.name 'github-actions[bot]'
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout data
      - name: Update CN ip
        run: |
          curl -sSL "https://github.com/vgist/cnip/raw/master/cnip-update.sh" -o cnip-update.sh
          chmod +x cnip-update.sh
          ./cnip-update.sh
          rm cnip-update.sh
      - name: Push Commits
        run: |
          git add cnv*.nft
          git diff-index --quiet HEAD || { git commit -m "${{ env.COMMIT_MSG }}" && git push -u origin data ; }
